apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: todo-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-app
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: todo-app
        controlledResources: ["cpu"]
        minAllowed:
          cpu: 50m
        maxAllowed:
          cpu: 500m
