prometheus:
  enabled: false
  prometheusSpec:
    retention: 3d
    externalUrl: "http://prometheus.cloudzen.me"
    routePrefix: /
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

grafana:
  enabled: false
  adminPassword: "changeme"
  grafana.ini:
    server:
      root_url: "http://grafana.cloudzen.me"

alertmanager:
  enabled: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
