resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.5/manifests/install.yaml

patches:
  - path: argocd-server-patch.yaml
    target:
      kind: Deployment
      name: argocd-server
